export const PAGE_PROPERTIES = { 
    ALL_COMMUNITIES: { key: "ALL_COMMUNITIES"},
    ALL_ACTIONS: { key: "ALL_ACTIONS"},
    ALL_EVENTS: { key: "ALL_EVENTS"},
    ALL_TEAM_MESSAGES: { key: "ALL_MESSAGES"},
    ALL_ADMIN_MESSAGES: { key: "ALL_ADMIN_MESSAGES"},
    ALL_TEAMS: { key: "ALL_TEAMS"},
    ALL_SUBSCRIBERS: { key: "ALL_SUBSCRIBERS"},
    ALL_TESTIMONIALS: { key: "ALL_TESTIMONIALS"},
    ALL_VENDORS: { key: "ALL_VENDORD"},
    ALL_USERS: { key: "ALL_USERS"},
    FEATURE_FLAGS: { key: "FEATURE_FLAGS"},
    OTHER_COMMUNITY_EVENTS: { key: "OTHER_COMMUNITY_EVENTS"},
} 


export const PAGE_KEYS = {
    CREATE_ACTION : { key:"CREATE_ACTION"},
    CREATE_EVENT : { key:"CREATE_EVENT"},
    CREATE_TEAM : { key:"CREATE_TEAM"},
    CREATE_VENDOR : { key:"CREATE_VENDOR"},
    PLACEHOLDER_PAGE : { key:"PLACEHOLDER_KEY"},
    CREATE_COMMUNITY : { key:"CREATE_COMMUNITY"},
    CREATE_POLICY : { key:"CREATE_POLICY"},
    CREATE_CARBON_EQ : { key:"CREATE_CARBON_EQ"},
    CREATE_NEW_TAG : { key:"CREATE_NEW_TAG"},
  
}

export const ME_FORM_PROGRESS = "ME_FORM_PROGRESS"