export const PAGE_PROPERTIES = { 
    ALL_COMMUNITIES: { key: "ALL_COMMUNITIES"},
    ALL_ACTIONS: { key: "ALL_ACTIONS"},
    ALL_EVENTS: { key: "ALL_EVENTS"},
    ALL_TEAM_MESSAGES: { key: "ALL_MESSAGES"},
    ALL_ADMIN_MESSAGES: { key: "ALL_ADMIN_MESSAGES"},
    ALL_TEAMS: { key: "ALL_TEAMS"},
    ALL_SUBSCRIBERS: { key: "ALL_SUBSCRIBERS"},
    ALL_TESTIMONIALS: { key: "ALL_TESTIMONIALS"},
    ALL_VENDORS: { key: "ALL_VENDORD"},
    ALL_USERS: { key: "ALL_USERS"},
    FEATURE_FLAGS: { key: "FEATURE_FLAGS"},
} 


export const PAGE_KEYS = {
    CREATE_ACTION : { key:"CREATE_ACTION"},
    CREATE_EVENT : { key:"CREATE_EVENT"},
    CREATE_COMMUNITY : { key:"CREATE_COMMUNITY"},
}

export const ME_FORM_PROGRESS = "ME_FORM_PROGRESS"