import avatarApi from '../images/avatars';
const emailData = [
  {
    id: '1',
    avatar: avatarApi[6],
    name: 'John Doe',
    date: 'May, 11 2018',
    subject: 'Hello',
    category: '',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '2',
    avatar: avatarApi[8],
    name: 'Jim Doe',
    date: 'May, 12 2018',
    subject: 'Hello',
    category: 'social',
    content: 'Hello',
    attachment: [],
    stared: true,
  },
  {
    id: '3',
    avatar: avatarApi[2],
    name: 'Jane Doe',
    date: 'May, 13 2018',
    subject: 'Vivamus sit',
    category: 'updates',
    content: 'Hello',
    attachment: [],
    stared: true,
  },
  {
    id: '4',
    avatar: avatarApi[9],
    name: 'Jinx Doe',
    date: 'May, 13 2018',
    subject: 'Hello',
    category: 'social',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '5',
    avatar: avatarApi[4],
    name: 'Jihan Doe',
    date: 'May, 15 2018',
    subject: 'Hello',
    category: 'promos',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '6',
    avatar: avatarApi[7],
    name: 'Johny Doe',
    date: 'May, 15 2018',
    subject: 'Hello',
    category: 'forums',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '7',
    avatar: avatarApi[5],
    name: 'Jane Doe',
    date: 'May, 16 2018',
    subject: 'Hello',
    category: 'spam',
    content: 'Hello',
    attachment: [],
    stared: true,
  },
  {
    id: '8',
    avatar: avatarApi[6],
    name: 'Me',
    date: 'May, 16 2018',
    subject: 'Hello',
    category: 'sent',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '9',
    avatar: avatarApi[7],
    name: 'James Doe',
    date: 'May, 17 2018',
    subject: 'Hello',
    category: 'sent',
    content: 'Hello',
    attachment: [],
    stared: true,
  },
  {
    id: '10',
    avatar: avatarApi[3],
    name: 'Jihan Doe',
    date: 'May, 17 2018',
    subject: 'Hello',
    category: 'sent',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
  {
    id: '11',
    avatar: avatarApi[10],
    name: 'Johny Doe',
    date: 'May, 20 2018',
    subject: 'Hello',
    category: 'spam',
    content: 'Hello',
    attachment: [],
    stared: false,
  },
];

export default emailData;
