import imgApi from '../images/photos';
const productData = [
  {
    id: '1',
    name: 'Hello',
    thumbnail: imgApi[21],
    desc: 'Hello',
    ratting: 4,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '2',
    name: 'Hello',
    thumbnail: imgApi[22],
    desc: 'Hello',
    ratting: 0,
    price: 15,
    prevPrice: 150,
    discount: '90%',
    soldout: false,
  },
  {
    id: '3',
    name: 'Hello',
    thumbnail: imgApi[23],
    desc: 'Hello',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '4',
    name: 'Hello',
    thumbnail: imgApi[24],
    desc: 'Hello',
    ratting: 2,
    price: 80,
    prevPrice: 100,
    discount: '20%',
    soldout: false,
  },
  {
    id: '5',
    name: 'Hello',
    thumbnail: imgApi[25],
    desc: 'Hello',
    ratting: 5,
    price: 50,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '6',
    name: 'Hello',
    thumbnail: imgApi[26],
    desc: 'Hello',
    ratting: 4,
    price: 75,
    prevPrice: 100,
    discount: '25%',
    soldout: false,
  },
  {
    id: '7',
    name: 'Hello',
    thumbnail: imgApi[27],
    desc: 'Hello',
    ratting: 5,
    price: 20,
    prevPrice: 16,
    discount: '20%',
    soldout: false,
  },
  {
    id: '8',
    name: 'Hello',
    thumbnail: imgApi[28],
    desc: 'Hello',
    ratting: 1,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '9',
    name: 'Hello',
    thumbnail: imgApi[29],
    desc: 'Hello',
    ratting: 4,
    price: 50,
    prevPrice: 100,
    discount: '50%',
    soldout: false,
  },
  {
    id: '10',
    name: 'Hello',
    thumbnail: imgApi[30],
    desc: 'Hello',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '11',
    name: 'Hello',
    thumbnail: imgApi[37],
    desc: 'Hello',
    ratting: 4,
    price: 66,
    prevPrice: 200,
    discount: '67%',
    soldout: false,
  },
];

export default productData;
